CI/CD updates (#1)
* test linux bundle ci

* workflows zip bundle

* Ubuntu ver 16.04

prevents Qt bundle error:
ERROR: The host system is too new.

* rm mysql-server due to apt errors

* workflow check release linux build

* include jspncpp dep in nimble builder

* workflows fix folly installation

* workflows linux revert to debug bundle

* workflows win cache deps

* Workflows fix win deps

* workflows fix syntax

* workflows debug

* workflows win debug 2

* workflows clear steps

* workflow linux junk-paths

* workflows fix cd

* workflows cache Qt, up Qt ver

* workflows debug linux path

* workflows linux upload build as artifact

* workflows win download debug deps, scoop debug

* workflows win debug

* workflows win fix command

* workflows fix Qt ver

* workflows cleanup, update debuglibs arch

* workflows update linux cache

* workflows fix indent

Co-authored-by: SirSevenG <44422309+SirSevenG@users.noreply.github.com>
Co-authored-by: SirSevenG <ottonseven@gmail.com>